server:
  port: 80
eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
# 添加返回超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
# hystrix设置超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
spring:
  application:
    name: cloud-provider-hystrix-order
logging:
  level:
    com.smile.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true